export const data = [
	{
		id: 1,
		name: "Open Season 2",
		popularity: 5.1,
		category: "Books",
		price: 10800,
		description: "Reverse-engineered context-sensitive strategy",
	},
	{
		id: 2,
		name: "Scooby-Doo! Camp Scare",
		popularity: 7.7,
		category: "Books",
		price: 16200,
		description: "Decentralized executive benchmark",
	},
	{
		id: 3,
		name: "Order, The",
		popularity: 6.5,
		category: "Books",
		price: 12000,
		description: "Configurable uniform extranet",
	},
	{
		id: 4,
		name: "Diamonds",
		popularity: 1.3,
		category: "Games",
		price: 9400,
		description: "Networked web-enabled moderator",
	},
	{
		id: 5,
		name: "MC5: Kick Out the Jams",
		popularity: 9.9,
		category: "Books",
		price: 15400,
		description: "Progressive incremental time-frame",
	},
	{
		id: 6,
		name: "Symmetry (Symetria)",
		popularity: 6.4,
		category: "Books",
		price: 16600,
		description: "Fully-configurable global functionalities",
	},
	{
		id: 7,
		name: "Manrape (Män kan inte våldtas) ",
		popularity: 1.2,
		category: "Books",
		price: 4600,
		description: "Ameliorated tertiary open architecture",
	},
	{
		id: 8,
		name: "Bride Flight",
		popularity: 1.2,
		category: "Books",
		price: 4200,
		description: null,
	},
	{
		id: 9,
		name: "Siberian Education (Educazione siberiana)",
		popularity: 1.4,
		category: "Books",
		price: 7400,
		description: "Realigned methodical support",
	},
	{
		id: 10,
		name: "Unleashed (Danny the Dog)",
		popularity: 3.1,
		category: "Books",
		price: 6900,
		description: null,
	},
	{
		id: 11,
		name: "In the Company of Men",
		popularity: 6.3,
		category: "Books",
		price: 5600,
		description: "Up-sized motivating workforce",
	},
	{
		id: 12,
		name: "Mentor",
		popularity: 8.5,
		category: "Music",
		price: 9600,
		description: null,
	},
	{
		id: 13,
		name: "Last Run",
		popularity: 1.6,
		category: "Books",
		price: 14200,
		description: null,
	},
	{
		id: 14,
		name: "Reel Bad Arabs: How Hollywood Vilifies a People",
		popularity: 1.7,
		category: "Books",
		price: 12700,
		description: "Optimized analyzing open architecture",
	},
	{
		id: 15,
		name: "Carpenter, The",
		popularity: 1.3,
		category: "Music",
		price: 12000,
		description: null,
	},
	{
		id: 16,
		name: "Moonfleet",
		popularity: 2.1,
		category: "Music",
		price: 15300,
		description: null,
	},
	{
		id: 17,
		name: "Key of Life (Kagi-dorobô no mesoddo)",
		popularity: 6.3,
		category: "Music",
		price: 17900,
		description: "Face to face demand-driven local area network",
	},
	{
		id: 18,
		name: "Wait Until Dark",
		popularity: 7.2,
		category: "Music",
		price: 13700,
		description: "Multi-lateral needs-based website",
	},
	{
		id: 19,
		name: "Fresh",
		popularity: 7.0,
		category: "Books",
		price: 6600,
		description: "Advanced mission-critical attitude",
	},
	{
		id: 20,
		name: "Jason Goes to Hell: The Final Friday",
		popularity: 3.4,
		category: "Music",
		price: 7700,
		description: null,
	},
	{
		id: 21,
		name: "Meja 1",
		popularity: 3.4,
		category: "Furniture",
		price: 770000,
		description: null,
	},
	{
		id: 22,
		name: "Kursi 1",
		popularity: 7.4,
		category: "Furniture",
		price: 972000,
		description: null,
	},
	{
		id: 23,
		name: "Meja 2",
		popularity: 9.2,
		category: "Furniture",
		price: 190700,
		description: null,
	},
	{
		id: 24,
		name: "Bola Lampu",
		popularity: 8.4,
		category: "Electronics",
		price: 9280,
		description: null,
	},
	{
		id: 25,
		name: "Toaster",
		popularity: 8.4,
		category: "Electronics",
		price: 177000,
		description: null,
	},
];
