insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (1, 'Buck Privates', 3.5, 'Clothing', 599490, 'Inverse upward-trending success');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (2, 'Forget Me Not', 6.6, 'Music', 541244, 'Self-enabling empowering monitoring');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (3, 'Alexander and the Terrible, Horrible, No Good, Very Bad Day', 2.6, 'Books', 167302, 'Adaptive stable matrix');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (4, 'Two Girls and a Guy', 7.2, 'Garden', 736610, null);
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (5, 'Nukes in Space', 9.3, 'Clothing', 1904643, 'Multi-layered context-sensitive synergy');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (6, 'Last Man Standing', 6.2, 'Jewelry', 1064329, null);
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (7, 'Smile', 3.3, 'Computers', 102643, 'Enterprise-wide dynamic customer loyalty');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (8, 'Doctor Who: The Time of the Doctor', 1.5, 'Home', 1800967, 'Robust mission-critical emulation');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (9, 'Siddhartha', 1.1, 'Music', 1934296, 'Reduced high-level time-frame');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (10, 'Sugar Hill', 8.0, 'Tools', 651734, 'Right-sized even-keeled software');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (11, 'Or (a.k.a. My Treasure)', 7.9, 'Baby', 1489695, 'Progressive logistical database');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (12, 'Bench, The (Bænken)', 2.1, 'Health', 1981841, 'Progressive mobile software');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (13, 'Youth of the Beast (Yaju no seishun)', 7.6, 'Garden', 65507, 'Switchable stable hardware');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (14, 'The Story of Robin Hood and His Merrie Men', 4.2, 'Health', 130588, null);
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (15, 'I Shot Andy Warhol', 8.9, 'Games', 448678, 'Innovative reciprocal utilisation');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (16, 'Along the Great Divide (Travelers, The)', 4.7, 'Baby', 1652529, 'Synergized empowering core');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (17, 'The Fault in Our Stars', 1.2, 'Health', 279637, 'Cross-platform zero administration encryption');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (18, 'Black Box, The (La boîte noire)', 9.2, 'Computers', 1007679, null);
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (19, 'Lovers on the Bridge, The (Amants du Pont-Neuf, Les)', 5.1, 'Sports', 1496598, 'Customer-focused value-added support');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (20, 'Citizen Koch', 8.5, 'Kids', 479224, 'Monitored regional projection');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (21, 'Twelve Tasks of Asterix, The (Les douze travaux d''Astérix)', 7.1, 'Grocery', 1019415, null);
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (22, 'Hamlet', 9.9, 'Grocery', 1234257, 'Grass-roots zero tolerance conglomeration');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (23, 'Rush Hour 2', 5.6, 'Jewelry', 468581, 'De-engineered neutral data-warehouse');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (24, 'Carry On... Up the Khyber', 3.9, 'Baby', 1938725, 'Expanded client-server workforce');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (25, 'American Hardcore', 8.3, 'Grocery', 904801, 'Self-enabling global open system');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (26, 'One to Another (Chacun sa nuit)', 4.2, 'Garden', 816310, 'User-friendly multi-tasking approach');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (27, 'Hell''s Gate 11:11', 4.4, 'Tools', 1145457, 'Optimized methodical concept');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (28, 'Valerie and Her Week of Wonders (Valerie a týden divu)', 6.2, 'Electronics', 1101523, 'User-friendly background frame');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (29, 'Autopsy', 9.3, 'Shoes', 654752, 'Visionary transitional approach');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (30, 'Matti: Hell Is for Heroes (Matti)', 1.6, 'Books', 1805557, 'Front-line solution-oriented attitude');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (31, 'M*A*S*H (a.k.a. MASH)', 3.4, 'Industrial', 1634314, null);
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (32, 'Deep Blue', 5.5, 'Home', 1000519, 'Up-sized real-time synergy');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (33, 'Frankenstein', 1.3, 'Toys', 1402009, 'Adaptive high-level open system');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (34, 'Trouble with the Truth, The', 2.3, 'Books', 1727811, 'Synergized interactive portal');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (35, 'Gervaise', 6.5, 'Games', 1755802, 'Fundamental encompassing Graphical User Interface');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (36, 'Hamburg Syndrome, The (Die Hamburger Krankheit)', 2.8, 'Beauty', 297269, null);
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (37, 'India (Indien)', 9.6, 'Toys', 708403, 'Phased local approach');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (38, 'Scooby-Doo! The Mystery Begins', 1.5, 'Industrial', 1660062, null);
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (39, 'Raisin in the Sun, A', 7.8, 'Games', 947638, 'Extended cohesive pricing structure');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (40, 'Independence Day (a.k.a. ID4)', 2.5, 'Home', 1286004, 'Organized user-facing adapter');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (41, 'Winter Soldier', 1.1, 'Sports', 1543458, 'Cross-group empowering knowledge user');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (42, 'Three (a.k.a. 3)', 1.6, 'Outdoors', 1014164, null);
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (43, 'Dick', 3.4, 'Shoes', 780610, 'Multi-layered 5th generation core');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (44, 'War Within, The', 2.7, 'Shoes', 86770, 'Public-key exuding array');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (45, 'How to Beat the High Cost of Living', 6.5, 'Games', 150836, 'Centralized solution-oriented extranet');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (46, 'Deuce Bigalow: Male Gigolo', 7.5, 'Books', 1666235, 'Programmable solution-oriented migration');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (47, 'Sound City', 3.4, 'Home', 1366585, 'Integrated grid-enabled task-force');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (48, 'Gojoe: Spirit War Chronicle (Gojo reisenki: Gojoe)', 8.9, 'Sports', 1785659, 'Inverse static model');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (49, 'My Brilliant Career', 4.4, 'Clothing', 85631, 'Profit-focused upward-trending parallelism');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (50, 'King of Kings', 8.9, 'Health', 74761, null);
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (51, 'National Security', 8.4, 'Industrial', 695501, 'Multi-tiered secondary architecture');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (52, 'Batman: The Dark Knight Returns, Part 2', 2.7, 'Shoes', 1954431, 'Innovative cohesive firmware');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (53, 'Real Men', 2.9, 'Grocery', 249840, 'Programmable coherent implementation');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (54, 'Enforcer, The', 9.5, 'Movies', 1621150, 'Realigned reciprocal archive');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (55, 'Noi the Albino (Nói albinói)', 3.9, 'Movies', 1322167, 'Open-source hybrid utilisation');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (56, 'Since You Went Away', 9.5, 'Electronics', 1636070, 'Cross-platform encompassing analyzer');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (57, 'Into the Abyss', 6.2, 'Tools', 1547862, 'Front-line regional task-force');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (58, 'False Trail (Jägarna 2)', 6.2, 'Shoes', 1294306, 'Decentralized national intranet');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (59, 'Mad Detective (Sun taam)', 6.8, 'Garden', 716006, 'Grass-roots systemic strategy');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (60, 'All Over Me', 4.2, 'Home', 327766, 'Enhanced optimal help-desk');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (61, 'Korso', 6.9, 'Computers', 81888, 'Quality-focused object-oriented conglomeration');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (62, 'Valmont', 3.5, 'Games', 716739, 'Face to face cohesive frame');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (63, 'Grudge, The', 6.9, 'Outdoors', 1684154, null);
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (64, 'Rain People, The', 1.7, 'Health', 1402081, 'Re-engineered homogeneous info-mediaries');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (65, 'Strada, La', 9.7, 'Books', 775782, 'User-friendly national frame');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (66, 'Hell Night', 6.0, 'Toys', 1864921, 'Optional eco-centric leverage');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (67, 'Leatherheads', 6.8, 'Outdoors', 1253747, 'Persistent dynamic adapter');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (68, 'Ashura', 8.9, 'Clothing', 1469920, 'Persevering bottom-line neural-net');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (69, 'Peace, Love & Misunderstanding', 5.0, 'Movies', 1339211, 'Triple-buffered analyzing methodology');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (70, 'Keeper, The', 9.8, 'Shoes', 1354006, 'Cross-platform interactive toolset');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (71, 'Support Your Local Sheriff!', 1.2, 'Movies', 1385216, 'Centralized static workforce');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (72, 'Isolation', 3.0, 'Beauty', 400420, null);
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (73, 'Strange Door, The', 6.9, 'Toys', 735392, 'Enhanced grid-enabled capability');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (74, 'Europeans, The', 4.6, 'Movies', 181188, 'Persistent demand-driven flexibility');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (75, 'Loputon Gehennan liekki', 2.2, 'Kids', 1118823, 'Advanced explicit task-force');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (76, 'Incredible Rocky Mountain Race', 2.3, 'Shoes', 1201261, 'Configurable reciprocal hierarchy');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (77, 'Awful Truth, The', 6.9, 'Toys', 996070, null);
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (78, 'Big Bad Wolf', 8.8, 'Toys', 414554, 'Pre-emptive logistical circuit');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (79, 'Portraits of Women (Naisenkuvia)', 8.0, 'Kids', 135997, 'Centralized regional hub');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (80, 'Elstree Calling', 2.1, 'Electronics', 892199, null);
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (81, 'At Any Second (In jeder Sekunde)', 6.7, 'Health', 1670701, 'Realigned responsive software');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (82, 'Signs', 5.4, 'Baby', 204852, 'Customizable uniform synergy');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (83, '13 Assassins (Jûsan-nin no shikaku)', 9.2, 'Health', 379117, 'Universal 5th generation standardization');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (84, 'Trinity and Beyond', 4.1, 'Beauty', 45051, null);
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (85, 'Hannah Arendt', 8.8, 'Jewelry', 109300, 'Monitored fresh-thinking contingency');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (86, 'Horseman on the Roof, The (Hussard sur le toit, Le)', 1.4, 'Sports', 1649108, null);
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (87, 'Dear Pillow', 5.9, 'Toys', 1730224, 'Streamlined coherent matrices');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (88, 'Jesus Christ Vampire Hunter', 2.2, 'Industrial', 70379, 'Phased hybrid firmware');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (89, 'Männerherzen... und die ganz ganz große Liebe', 8.7, 'Shoes', 1522568, 'Front-line systemic access');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (90, 'Kiss Me Deadly', 8.7, 'Kids', 1759518, 'De-engineered needs-based project');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (91, 'Charlie Chan at Treasure Island', 8.3, 'Baby', 1642518, 'Customer-focused 24 hour budgetary management');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (92, 'Cat''s Meow, The', 8.4, 'Industrial', 1865203, 'Polarised transitional paradigm');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (93, 'Film with Me in It, A', 3.8, 'Computers', 884530, 'Enterprise-wide 4th generation migration');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (94, 'Go Get Some Rosemary (Daddy Longlegs)', 2.1, 'Baby', 1100376, 'Sharable fault-tolerant standardization');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (95, 'Millennium Actress (Sennen joyû)', 4.8, 'Computers', 650801, null);
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (96, 'Two Weeks in Another Town', 4.4, 'Books', 568887, 'Assimilated eco-centric protocol');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (97, 'Mating Season, The', 6.7, 'Shoes', 910303, 'Future-proofed 4th generation extranet');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (98, 'Gorgon, The', 7.8, 'Movies', 1773533, 'Diverse 24 hour frame');
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (99, 'Day of the Dead', 7.8, 'Automotive', 1339798, null);
insert into MOCK_DATA (id, item_name, popularity, category, price, item_description) values (100, 'Anima Mundi', 6.1, 'Movies', 1668950, 'Profound secondary challenge');
